/*
package com.zhd.dao;


import com.zhd.model.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentMapper {
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    int deleteByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    int insert(Student record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    Student selectByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    List<Student> selectAll();

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    int updateByPrimaryKey(Student record);
}*/
