/*
package com.zhd.dao;


import com.zhd.model.Teacher;
import com.zhd.model.TeacherExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TeacherMapper {
    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int countByExample(TeacherExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int deleteByExample(TeacherExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int deleteByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int insert(Teacher record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int insertSelective(Teacher record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    List<Teacher> selectByExample(TeacherExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    Teacher selectByPrimaryKey(Integer id);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int updateByPrimaryKeySelective(Teacher record);

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    int updateByPrimaryKey(Teacher record);
}*/
