/*
package com.zhd.model;

import java.io.Serializable;

public class Student implements Serializable {
    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private Integer id;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private String name;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private String password;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private String email;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.remark
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private String remark;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    private static final long serialVersionUID = 1L;

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public Integer getId() {
        return id;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public void setId(Integer id) {
        this.id = id;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public String getName() {
        return name;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public String getPassword() {
        return password;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public String getEmail() {
        return email;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remark
     *
     * @return the value of student.remark
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public String getRemark() {
        return remark;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remark
     *
     * @param remark the value for student.remark
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 05 07:02:56 CST 2018
     *//*

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}*/
