/*
package com.zhd.model;

import java.io.Serializable;
import java.util.Date;

public class Teacher implements Serializable {
    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private Integer id;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private String name;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.address
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private String address;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.create_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private Date createTime;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.update_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private Date updateTime;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.remark1
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private String remark1;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.remark2
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private String remark2;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.flage_able
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private String flageAble;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.s_id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private Integer sId;

    */
/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    private static final long serialVersionUID = 1L;

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public Integer getId() {
        return id;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setId(Integer id) {
        this.id = id;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public String getName() {
        return name;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.address
     *
     * @return the value of teacher.address
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public String getAddress() {
        return address;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.address
     *
     * @param address the value for teacher.address
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.create_time
     *
     * @return the value of teacher.create_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public Date getCreateTime() {
        return createTime;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.create_time
     *
     * @param createTime the value for teacher.create_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.update_time
     *
     * @return the value of teacher.update_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public Date getUpdateTime() {
        return updateTime;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.update_time
     *
     * @param updateTime the value for teacher.update_time
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.remark1
     *
     * @return the value of teacher.remark1
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public String getRemark1() {
        return remark1;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.remark1
     *
     * @param remark1 the value for teacher.remark1
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.remark2
     *
     * @return the value of teacher.remark2
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public String getRemark2() {
        return remark2;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.remark2
     *
     * @param remark2 the value for teacher.remark2
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.flage_able
     *
     * @return the value of teacher.flage_able
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public String getFlageAble() {
        return flageAble;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.flage_able
     *
     * @param flageAble the value for teacher.flage_able
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setFlageAble(String flageAble) {
        this.flageAble = flageAble == null ? null : flageAble.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.s_id
     *
     * @return the value of teacher.s_id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public Integer getsId() {
        return sId;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.s_id
     *
     * @param sId the value for teacher.s_id
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    public void setsId(Integer sId) {
        this.sId = sId;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Fri Oct 05 09:15:42 CST 2018
     *//*

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", flageAble=").append(flageAble);
        sb.append(", sId=").append(sId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}*/
